Fig = figure('Name', 'Interface', ...
    'NumberTitle', 'off', ...
    'Position', [400 300 600 400], ...
    'Color', [0.8500 0.3250 0.0980]);

% background image
w = imread('1649074ecd03634e05639d767e131258.jpg');
imshow(w, 'InitialMagnification', 500);


%the menu
h = uimenu('Label','Meniu');
%creates the menu item that displays the Project Front Page
uimenu(h,'Label','Front Page','Callback','front_page_1');
uimenu(h,'Label','Documentation','Callback','documentatie');


% Create label and edit field for input voltage
uicontrol('Style', 'text', 'Units', 'normalized', ...
    'Position', [0.2, 0.6, 0.2, 0.1], ...
    'String', 'Input Voltage (V):');
inputVoltageEdit = uicontrol('Style', 'edit', 'Units', 'normalized', ...
    'Position', [0.4, 0.6, 0.2, 0.1]);

% Create a label for the positive peak detector result
positiveResultLabel = uicontrol('Style', 'text', 'Units', 'normalized', 'Position', [0.2, 0.45, 0.2, 0.1], 'String', 'Positive Peak:');

% Create a label for the negative peak detector result
negativeResultLabel = uicontrol('Style', 'text', 'Units', 'normalized', 'Position', [0.2, 0.3, 0.2, 0.1], 'String', 'Negative Peak:');


%Buttons for displaying the circuits TMAX and TMIN
uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.15 0.8 0.3 0.1], ...
    'String', 'Circuit Temporal Max Two-Port', ...
    'Callback', 'TMAX');

uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.60 0.8 0.3 0.1], ...
    'String', 'Circuit Temporal Min Two-Port', ...
    'Callback', 'TMIN');

% New button for calculating and displaying the positive peak result
positiveCalculateButton = uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.7 0.52 0.2 0.08], ...
    'String', 'Calculate Positive Peak', ...
    'Callback', {'output_voltage_POZ', inputVoltageEdit, positiveResultLabel});

% Button for calculating and displaying the negative peak result
negativeCalculateButton = uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.7 0.35 0.2 0.08], ...
    'String', 'Calculate Negative Peak', ...
    'Callback', {'output_voltage_NEG', inputVoltageEdit, negativeResultLabel});

% Button for Positive Peak Chart
positiveChartButton = uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.25 0.1 0.2 0.1], ...
    'String', 'Positive Peak Chart', ...
    'Callback', {'time', 'positive', inputVoltageEdit});

% Button for Negative Peak Chart
negativeChartButton = uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.65 0.1 0.2 0.1], ...
    'String', 'Negative Peak Chart', ...
    'Callback', {'time', 'negative', inputVoltageEdit});

%Button for closing the interface
uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.15 0.15 0.1], ...
    'String', 'CLOSE', ...
    'ForegroundColor', 'g', ...
    'Callback', 'close');

