function Circuit_Temporal_Max_Two_port

Fig=figure('Name','TMAX',...
'NumberTitle','off');
w= imread('T_MAX.jpeg'); 
imshow(w, 'InitialMagnification', 100); 
title('Temporal Max Two port');


uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.75 0.03 0.2 0.08],...
'String','CLOSE',...
'Callback','close;');
end